language: android

branches:
  only:
    - master
    - develop

android:
  components:
   - tools
   - platform-tools
   - build-tools-25.0.2
   # sdk version in project
   - android-25

   # Additional components
   # Using design support library
   - extra-android-m2repository

   # Using google play services
   - extra-google-m2repository

before_script:
 - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &

script:
 - ./gradlew build connectedCheck

jdk: oraclejdk8

after_failure:
 - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

notifications:
  slack:
    secure: B+H3BJ04MAi+4bcyb9+4aW4rDlMhw9iBsqYCCGtW2WUQyvxyGIWgz/j7RuHG+A9e7NreG5z6g+b+mdGEXUd2DooxwOheUOoIGF9JEpa2WD2OVQfwKdsKyOXG7AJKB75za9nEZxDmaaUj9Rtl37DqD8abUvaAQx6v/F2/opmdjLaeH49nSNREkbflY+9iBsU3JsOTEB5FjMr/RLE10UN7b0OGYQ6Wl+/kUHOxmIrD2PBnJRwD/PhFXxMTeblm0lHYky53FG4FhSUW8e6uWnccYB+nNyiWvIfeusaPXleBNIpX3n3nCi5mnRLfBowsN/6kvBYwmBsBMcPuvWfmjSAdNrojSgnN7KdHPo65lid88Ptz9sW1zyqMPXjOuaU1bAs8meUWW421CBuY730YSg9MJcLHkQqKAlNIgnW5xGGMkSXISCo9fdLqUmZJ0r2nxjZkoLsFMN5oaikHRdJxQmbDCx2mzYI/urgeKywLLe5XuRcJGStXab0k8tujXgefYWj05GgwFtvT6KJvXkDScW794nL4TSVMWSLrV+tuMSbLVFFH1+nmdbxkOx5xJRAZL2fwyzQegBaI+3VikZJZ0bMIP+smR8cElImiYQ5VjGUQkdVuoUDv2vs0hltbgewg0BBSg9DEBcFL/buJLCCto98P7ldigeFVlcTq0Cdsw2ZCiQQ=
  email:
    on_success: never
    on_failure: never
