language: android

env:
  global:
   - secure: "iEY8djvj0824GX64blYa545fQtOFL/k+nlKon9hHlhodqn+wJ9FAA8jk6dT4DSHzbQEPy3X9JCi8jVfecyGryYrmywEhKYCJCyuW7xce5ryLAaqe5k8oNKkzbvK3vr5FyCuYac/9S8nXfdstdrnplwyXuEBFdMyjiFjdFGCaqsi52gXpJaogFA1APBqOTCnmHnYneKYMERhAvpfd1vs+wUtanNhu8UTDy073FzbIo6MjvL6VJtpmKM9ZZunv5mJY3utxD2cGTkWHArc49XHv4qsyA2txHNa7vQMOFWg3ZMCmLUTwlnELjNWZrBscX6/pL0MlFYmy1YkD5L9B1mGnLQ2HDuBQQIl+i/rbgi7Hswse2RNo/uMziPYViJuSdEfUk7iy5hQkw9Aj6C/FdWKr4xwcuKIYrtrzmRd+cl3S0S4PnrWgUuAaqFDDvS87SY64FKRxyLN1vv0LEDjXxUiljmuuEsCSXW2rsx0wTj7Aqjnpl2Z/s13aHOM+vdu3ECyC/ZU0kHmA+e+DIX9366EQi45dOGHtHXX9KKmaMvnS69iiKKBIAooVyo5+TZY6oncW5nAh82qOrGxcXA6Hes69pski52zqLrvSzaCyZOrljgYSkCBNcM0dwAep83PktSUlgsRHf5ebCkDJjCFGwbh3CUQHrrLw8T1d6txvz1txf74="
   - secure: "SrhHXYxEQDqIaQx2BLHV0PjPqgOMd53kZSbmH98XgB+fp9rx2nScNGfsdTApo5QJTjA3kvgDgdtN07cKXybgNmwNjP9znajZAQeJBqpPfXc5pUrZlf13uPPD31QFZQt1VuCvf+TvPzH1TdPGaEL6Q3deR87qu+/Vg4TsxTNpgj3tPx6uSk1YuGe8sO3axcTU6R+LD6HLbza8G8WmQFoURPenkBL0PDPCaXQVokXpHxiRTDIgpSpjoQClFimTf93LwCmVQTqclyTZmhEZMwuoYB5htpkrXTNXV8zh6At2bwJ+zewhXTnXDjBelWudMhRXEsvF1dBmECcZ1bIvao/AqZMOMclKELp7aCwaylpUeUfVBDsBCOx90HJ0qmf6VcgTSrRht2cTU2RCIzhaWmxPz4xOBB2yyeMGlBntRPKYxm9Fc8keWq+TB8KNk5nOFD9g6zqbpyJnsFcIVkAORCc97Gf/i6udlTbUeC1uitnL7StFaWbKA7Mg2KavuJfe8KY8ErLPXmOBC7PjM0gMpuXcZ0hbefpzpRIV8ddNLtvgLCiS9j/PL/3puhvudJMxSahxbgHfvjyIAtr/jDoY11d6fBmEKcBR4GyndHgDuv9noaKeyxP1+QSssMtoLywEWsIDRDBKgg3NeBuQpJKl6a6D+ZoC0I0gXdJ2h78pVo+61xM="

branches:
  only:
    - master
    - develop

android:
  components:
   - tools
   - platform-tools
   - build-tools-25.0.2
   # sdk version in project
   - android-25

   # Additional components
   # Using design support library
   - extra-android-m2repository

   # Using google play services
   - extra-google-m2repository

before_script:
 - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -prop persist.sys.language=ja
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &

script:
 - ./gradlew build connectedCheck coveralls

jdk: oraclejdk8

after_success:
 - test $TRAVIS_PULL_REQUEST = "false" && test $TRAVIS_BRANCH = "develop" && ./gradlew uploadDeployGateDebug

after_failure:
 - cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml

notifications:
  slack:
    secure: B+H3BJ04MAi+4bcyb9+4aW4rDlMhw9iBsqYCCGtW2WUQyvxyGIWgz/j7RuHG+A9e7NreG5z6g+b+mdGEXUd2DooxwOheUOoIGF9JEpa2WD2OVQfwKdsKyOXG7AJKB75za9nEZxDmaaUj9Rtl37DqD8abUvaAQx6v/F2/opmdjLaeH49nSNREkbflY+9iBsU3JsOTEB5FjMr/RLE10UN7b0OGYQ6Wl+/kUHOxmIrD2PBnJRwD/PhFXxMTeblm0lHYky53FG4FhSUW8e6uWnccYB+nNyiWvIfeusaPXleBNIpX3n3nCi5mnRLfBowsN/6kvBYwmBsBMcPuvWfmjSAdNrojSgnN7KdHPo65lid88Ptz9sW1zyqMPXjOuaU1bAs8meUWW421CBuY730YSg9MJcLHkQqKAlNIgnW5xGGMkSXISCo9fdLqUmZJ0r2nxjZkoLsFMN5oaikHRdJxQmbDCx2mzYI/urgeKywLLe5XuRcJGStXab0k8tujXgefYWj05GgwFtvT6KJvXkDScW794nL4TSVMWSLrV+tuMSbLVFFH1+nmdbxkOx5xJRAZL2fwyzQegBaI+3VikZJZ0bMIP+smR8cElImiYQ5VjGUQkdVuoUDv2vs0hltbgewg0BBSg9DEBcFL/buJLCCto98P7ldigeFVlcTq0Cdsw2ZCiQQ=
  email:
    on_success: never
    on_failure: never
